### ISSUE TITLE
bookmarks-button.js - sorting messes up custom order of bookmarks

### ISSUE THREAD

**Issue by tophf** [justdanpo/VivaldiHooks#1]
Currently bookmarks-button.js sorts the bookmarks and thus totally messes up the order customized by a user in Bookmarks. I've disabled it locally and I suggest to do the same in the script here.

**Comment by justdanpo** [comment]
bookmarks-button.js follows sort settings of the bookmarks panel

**Comment by tophf** [comment]
It's `Sort manually` in my case which means I've rearranged items manually.  No automatic sorting.

**Comment by justdanpo** [comment]
bookmarks-button.js displays items in exactly the same order as Bookmarks Panel.
Don't you mix it with patches?

**Comment by tophf** [comment]
Only when I edit bookmarks-button.js and comment out the following line `//treeSort.treeSort(data, comparator);` it shows my bookmarks in customized order correctly. Otherwise it's completely different.

My `hooks` folder contains these js files:

```
alt-key-menu.js
bookmarks-button.js
copy-searchfield.js
create-tab-with-middle-click.js
extensions-buttons-menu-settings.js
fix-search-favicons.js
fix_first_tab_switch.js
loading.js
new-notes-at-the-top.js
newtab-middleclick-pasteandgo.js
qc-close-tab.js
search-selected.js
searchfield-current-engine-icon.js
select-urlfield.js
unicode-url.js
zoom-buttons.js
zoom-control-wheel.js
```

**Comment by justdanpo** [comment]
OK, I've reproduced it with a clean profile.

**Comment by justdanpo** [comment]
https://github.com/justdanpo/VivaldiHooks/commit/16c2cb4511d8a060d0f9d03dbc7b0c5d8810e07c

**Comment by tophf** [comment]
Yay! It works now.
