### ISSUE TITLE
middle click stopped working in the bookmarks-button.js

### ISSUE THREAD

**Issue by raszpl** [justdanpo/VivaldiHooks#12]
used to work fine in ~1.6. Updated today to 1.7.735.11, installed VivaldiHooks and it no longer works :(

**Comment by JevonChu** [comment]
1.7.735.46(stable) middle click can‘t open new tab.

**Comment by justdanpo** [comment]
Have you tried updating VivaldiHooks?

**Comment by JevonChu** [comment]
updated，1.6，bookmarks-button.js left-click open in the current tab，middle-click open in the new tab  . 1.7，it doesn't work.. sorry my bad english

**Comment by justdanpo** [comment]
I'm sorry, I've misreaded.
bookmarks-button.js inherits bookmarks bar's behaviour. There is a bugreport: VB-25215 - "Middleclick on bookmarks under the chevron icon opens bookmarks in current tab".

**Comment by justdanpo** [comment]
Fixed in 1.8
