### ISSUE TITLE
Hook for V settings is broken

### ISSUE THREAD

**Issue by Vladimyr0** [justdanpo/VivaldiHooks#13]
V settings screen is blank (white). when I remove jdhooks-startup-settings.js from the folder, settings do back no normal operation. (Win7 64, 1.8.755.3)

**Comment by justdanpo** [comment]
Are you sure you're using the latest version of VivaldiHooks?

**Comment by Vladimyr0** [comment]
The very last version (commit bf483e2) doesn't have this problem.
