### ISSUE TITLE
vendor-bundle.js needs fixing after version 1.8.770.9

### ISSUE THREAD

**Issue by nicobustillos** [justdanpo/VivaldiHooks#16]
VivaldiHooks have been working nicely up to vivaldi-snapshot_1.8.770.9-1. Every new snapshot after that will not launch after VivaldiHooks is installed (including vivaldi-snapshot_1.8.770.44, which is Release Candidate 1 for vivaldi-stable 1.8). It seems to be related to the file vendor-bundle.js, because as soon as you restore the original file from vivaldi-snapshot it launches normally again (but of course VivaldiHooks are no longer there).
Maybe there was a major change in this file (a file that is required to be replaced by VivaldiHooks installation)?

**Comment by justdanpo** [comment]
Works for me.
I need more details about OS and Vivaldi version you use.

**Comment by nicobustillos** [comment]
Ouch. I feared that. 

So my OS is Kubuntu 16.04 (KDE Plasma 5.8.5 and Linux Kernel 4.4.0-70) 64-bit.
I've tried with two different versions of Vivaldi Snapshot: 1.8.770.32 and 1.8.770.44. Both displayed the same problem (but 1.8.770.9 works fine every time)

Is there any other place I should look for logs of something?
Also another question... when you first install VivaldiHooks and it prompts you to download and copy "vendor-bundle.js", where does it download from? And is it always the same file regardless of the version of Vivaldi? Thanks a lot.

**Comment by ddnexus** [comment]
Same problem with 1.8.770.50 (Stable channel) (64-bit) (Ubuntu 16.10). 

I even tried with an empty hooks dir: after generating the vendor-bundle.js and replacing it, the processes start (you can see them with ps), but the UI doesn't appear. You can launch another instance from the terminal and it adds the window process, but again, no trace of the UI.

**Comment by justdanpo** [comment]
Are you sure it's not about access rights?

I'll try rewriting jdhooks.js so it wouldn't require updating vendor-bundle.js.

**Comment by ddnexus** [comment]
What should be the group, owner and permission of that file (and any jdhooks file involved)?

BTW, removing the need of updating the file would be a very nice improvement!

**Comment by ddnexus** [comment]
You were right!

In my case the hooks dir was copied with no access for anybody but root, and the vendor-bundle.js was missing the read permission for all.

Adding a more detailed note in the installation doc would probably be useful for other users.

**Comment by justdanpo** [comment]
> BTW, removing the need of updating the file would be a very nice improvement!

https://github.com/justdanpo/VivaldiHooks/commit/d7e62b9acdfa87c1fe448d935f554fa51fec968d

**Comment by nicobustillos** [comment]
Great, it works again. I'm back with the latest snapshot version and VivaldiHooks is working great.

In my case I'pretty sure it wasn't an access or permission issue. But that last commit sure did the trick by removing the patching requirement. Great work! Thanks for adding great value on Vivaldi.
