### ISSUE TITLE
status bar at the bottom

### ISSUE THREAD

**Issue by stla** [justdanpo/VivaldiHooks#17]
Hello, 
 After installing the hooks, the "status bar" (zoom, capture page, etc) goes to the top of the window. How to put it at the bottom ?

**Comment by justdanpo** [comment]
![jdhooks-startup-settings.png](https://github.com/justdanpo/VivaldiHooks/raw/master/screenshots/jdhooks-startup-settings.png)

**Comment by stla** [comment]
All these options are checked for me, but the status bar is at the top.

**Comment by stla** [comment]
![capture](https://cloud.githubusercontent.com/assets/4466543/24581217/ac594d0e-1717-11e7-8104-c47f8284fed6.PNG)

**Comment by justdanpo** [comment]
What do you think these checkboxes do?

**Comment by stla** [comment]
Sorry, but I don't understand your replies. 
I see nothing related to the location of the status bar.

**Comment by stla** [comment]
Maybe I was not clear (I'm not an eminent English speaker). 
For example, the zoom slider was at bottom right before I installed the hooks. Now it is at top right.

**Comment by stla** [comment]
Solved ! 
I've deleted the file `statusbar-at-the-top.css` in the `hooks` folder.
Thank you.
