### ISSUE TITLE
Bookmark Button works but has no icon

### ISSUE THREAD

**Issue by ddnexus** [justdanpo/VivaldiHooks#18]
It looks like it is missing the pict: the space and the functionality are there but there is no icon.

**Comment by justdanpo** [comment]
Cannot reproduce

**Comment by ddnexus** [comment]
Maybe it is a local thing here. What should I check in order to find out the possible cause?

**Comment by justdanpo** [comment]
I've found one case
https://github.com/justdanpo/VivaldiHooks/commit/417d8e139657fec4d0e6e7f3be78933ffb4839a9
Please check.

**Comment by ddnexus** [comment]
It works now!. Thanks!
