### ISSUE TITLE
How to uninstall it? 

### ISSUE THREAD

**Issue by Droyk** [justdanpo/VivaldiHooks#2]
Plz don't tell me I can't plz

**Comment by PunchyRascal** [comment]
I think you just need to remove one line in file `c:\Program Files (x86)\Vivaldi\Application\1.4.xxx\resources\vivaldi\browser.html`

remove the line: `<script src="jdhooks.js"></script>`

worked for me

**Comment by justdanpo** [comment]
Updated README.md
