### ISSUE TITLE
searchfield-current-engine-icon doesn't work anymore

### ISSUE THREAD

**Issue by Vladimyr0** [justdanpo/VivaldiHooks#23]
affected a couple of the latest vivaldi builds.
downloaded current hooks just a minute ago and checked on the fresh installation.

**Comment by justdanpo** [comment]
Check the latest update https://github.com/justdanpo/VivaldiHooks/commit/ea02bb412806d49cba976572a8271cd6a9127650

**Comment by Vladimyr0** [comment]
solved. thank you Sir!

**Comment by Vladimyr0** [comment]
in 1.11.917.17, it happens again.

**Comment by justdanpo** [comment]
Not applicable anymore
