### ISSUE TITLE
move-V-button-to-addressbar.js does not show the V on the button

### ISSUE THREAD

**Issue by dadrc** [justdanpo/VivaldiHooks#25]
Activating the _move-V-button-to-addressbar.js_ hook moves the button to the address bar as intended, but the button is missing the Vivaldi V (see attached screenshot).

![vivaldi_hook](https://user-images.githubusercontent.com/1412540/27285750-fb417d8c-54fd-11e7-9f47-1272746f6569.png)

VilvaldiHooks from git (058f1f0ee519a87e89c8ec19037a54493b657d4d)
Vivaldi 1.10.867.38 (Stable channel) (64-bit)
Ubuntu 16.04

**Comment by hababr** [comment]
Same issue, Windows 10.

**Comment by natanvarga** [comment]
Can confirm. Arch Linux.

**Comment by justdanpo** [comment]
Switched to another V icon
https://github.com/justdanpo/VivaldiHooks/commit/ea02bb412806d49cba976572a8271cd6a9127650

**Comment by dadrc** [comment]
Thanks, that fixed my problem.
