### ISSUE TITLE
1.11.894.3: some hook prevents Vivaldi from showing any windows

### ISSUE THREAD

**Issue by alexpolozov** [justdanpo/VivaldiHooks#28]
After I updated Vivaldi to the latest build (1.11.894.3) and installed the latest snapshot of this repo, Vivaldi stopped displaying any windows. Specifically, when I launch it, it creates all the usual processes in the background (graphical and non-graphical alike), but no windows appear. To clarify, they actually _do not appear_, rather than appear off-screen or on a different desktop/monitor. There are no windows in `Alt+Tab` or `Win+Tab`, but their corresponding processes are running in the background. This problem disappears when I uninstall the hooks.

#### Questions

1. How can I find out which specific hook is responsible?
2. How can I turn the hooks on/off without launching Vivaldi?

#### System details

```
Vivaldi	1.11.894.3 (Official Build) (64-bit)
Revision	b59976a912279d9a89261a23da2159400e8a40d4
OS	Windows
JavaScript	V8 5.9.211.38
Flash	26.0.0.131 C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_26_0_0_131.dll
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.112 Safari/537.36 Vivaldi/1.92.894.3
Command Line	"C:\Users\Alex\AppData\Local\Vivaldi\Application\vivaldi.exe" --always-authorize-plugins --disable-translate --enable-blink-features=ResizeObserver --ppapi-flash-path="C:\WINDOWS\system32\Macromed\Flash\pepflashplayer64_26_0_0_131.dll" --flag-switches-begin --enable-canvas-2d-dynamic-rendering-mode-switching --enable-fast-unload --enable-offline-auto-reload-visible-only --enable-scroll-prediction --save-page-as-mhtml --show-autofill-type-predictions --enable-features=AsmJsToWebAssembly,AutomaticTabDiscarding,OverlayScrollbar,SharedArrayBuffer,WebAssembly --flag-switches-end
Executable Path	C:\Users\Alex\AppData\Local\Vivaldi\Application\vivaldi.exe
Profile Path	C:\Users\Alex\AppData\Local\Vivaldi\User Data\Default
Compiler	MSVC 2015
```

**Comment by FlyNeko48** [comment]
Hooks are files in Vivaldi\Application\1.11.894.3\resources\vivaldi\hooks. You can turn them off simply removing them one by one until you find out which ones are breaking Vivaldi.

**Comment by justdanpo** [comment]
Check the latest update
https://github.com/justdanpo/VivaldiHooks/commit/ea02bb412806d49cba976572a8271cd6a9127650

**Comment by alexpolozov** [comment]
@justdanpo Works now. Thanks!
