### ISSUE TITLE
Settings page doesn't show hooks enable/disable on Vivaldi 1.11

### ISSUE THREAD

**Issue by thx1200** [justdanpo/VivaldiHooks#29]
Since upgrading to Vivaldi 1.11, the section in the settings that lets you enable/disable hooks is not showing up.

**Comment by Kabouik** [comment]
Same issue here on Vivaldi 1.11.917.39 (Stable channel) 64-bit for Linux.

**Comment by JevonChu** [comment]
bookmarks-button.js also doesn't work for 1.11.917.39.

**Comment by raszpl** [comment]
`jdhooks: unknown module AddressBarDropdown
jdhooks.js:725 jdhooks: unknown module AddWebPanelButton
jdhooks.js:725 jdhooks: unknown module AttachmentItem
jdhooks.js:725 jdhooks: unknown module autoupdate
jdhooks.js:725 jdhooks: unknown module BackgroundTaskStatus
jdhooks.js:725 jdhooks: unknown module BackgroundTaskStatusList`

**Comment by thx1200** [comment]
Issue still exists in latest stable build 1.11.917.43

**Comment by raszpl** [comment]
1.11.904.3 is the last working build. We need someone who understands Vivaldi react spaghetti enough to patch jdhooks for never builds.

**Comment by thx1200** [comment]
That's way outside my area of expertise.  I'm a beginner in JS...

**Comment by thx1200** [comment]
Is anybody maintaining this project or is it dead?

**Comment by amayer5125** [comment]
@raszpl How did you get that output?

**Comment by raszpl** [comment]
dev console. its standard jdhooks.js debug output

**Comment by raszpl** [comment]
btw even with hooks not working in 1.12 some JS is still executed

you can see it opening Settings, Hooks section is randomly injected into every tab (should be only in Startup), so there definitely is a possibility of fixing it with some elbow grease even without understanding what the deal with jdhooks/react is.

**Comment by justdanpo** [comment]
Not applicable anymore
