### ISSUE TITLE
Bookmarks button doesn't work

### ISSUE THREAD

**Issue by inconspicuous007** [justdanpo/VivaldiHooks#30]
The bookmarks button doesn't appear as shown in the screenshot.
I have manually tried adding bookmarks-button.js to browser.html but, it's still the same.

**Comment by SwanKnight** [comment]
Same issue here.

**Comment by EleanorEllis** [comment]
There is now a bookmarks button in the address bar. Did the hook do anything different? Or could the hooks bookmarks button now be retired?
