### ISSUE TITLE
loading module doesn't start "spinning" until page content loads in Vivaldi 1.11

### ISSUE THREAD

**Issue by thx1200** [justdanpo/VivaldiHooks#31]
The spinner doesn't start spinning until the page content starts loading, meaning that previously as soon as you clicked a link or a button, the spinner started, giving you a visual indication the click actually worked.  Now this is not the case.  I can't tell if both the loading css and js are enabled because of the other issue where the config page no longer loads in V1.11.  But it was before I upgraded.

Windows 10, Creators, Vivaldi 1.11.917.43 (Stable channel) (32-bit)

**Comment by justdanpo** [comment]
Fixed
