### ISSUE TITLE
Vivaldi cannot start with jdhooks

### ISSUE THREAD

**Issue by ddnexus** [justdanpo/VivaldiHooks#32]
Vivaldi Version: 1.13.1008.32 (Stable channel) (64-bit) Linux

Vivaldi launches and stops on a blank page. Trying to launch it from the terminal:

ATTENTION: default value of option force_s3tc_enable overridden by environment.

Removing jdhooks.js from browser.html allows Vivaldi to start, but obviously there will be no hooks. :/

**Comment by Thefirsh** [comment]
I also experience the same thing. Is there a workaround for the time being?

**Comment by ddnexus** [comment]
I downgraded Vivaldi :/

**Comment by thx1200** [comment]
Same, VivaldiHooks is completely broken in 1.13.  They must have done some big under the hood changes.  There were a bunch of bugs still in 1.12 and I haven't seen really much activity here, so unless somebody still following this project heroes up, this may be it for Hooks.  :-(  I am willing to volunteer what time I can, but I just don't know javascript much beyond like the alert box, so I don't know how much help I'll be.  I looked at the source code bewildered.  haha.

**Comment by jdunne525** [comment]
Warning: I don't know Javascript from Greek, but I managed to get at least multiline tabs working (I suspect this method should work for any of the CSS type hooks)

In this folder:
Create a file load_hooks.js with this contents (modify for the various hooks you'd like to load):

```
(function() {

	Elem = document.createElement("link");
	Elem.href = "hooks/multiline-tabs.css";
	Elem.rel = "stylesheet";

	document.head.appendChild(Elem);
})();
```

Edit browser.html:
Add this line before bundle.js (where jdhooks.js would normally be loaded):
`    <script src="load_hooks.js"></script>
`

**Comment by ddnexus** [comment]
Another possible working solutionis loading the .js directly with a script tag:

```html
<script src="hooks/move-V-button-to-addressbar.js"></script>
```

**Comment by Yodzorah** [comment]
C'mon, it's obviously an abadoned pack of hooks, and, truth be told, there's almost nothing useful left in here - Vivaldi'd already implemented pretty much of it. You could've already learn JS and write your own hooks pack for whatever you want instead of downgrading the browser and waiting for nothing.

**Comment by ddnexus** [comment]
@Yodzorah: C'mon, it's obvious that "almost" is something in this case! :)

Try to use the linux version with the vanilla Vivaldi and you will be greeted by a useless empty bar on top of the window that sucks up real estate (and coolness) for no reason. I reported that bug many months ago but it's obvious it still didn't make it to the "pretty much of it" that you mention.

**Comment by Yodzorah** [comment]
@ddnexus, same story with passive scrolling for me. And yet, I think, there's no sense in waiting for the fix (or asking for new features) here. I've already wrote a script for current search icon displaying and I'm gonna write another one for passive scrolling, because there is really no hope the repo will suddenly come to live. How long has it been since the repo came out of date? You could have already learn JS yourself and write a simple, but working script)

`Try to use the linux version with the vanilla Vivaldi and you will be greeted by a useless empty bar on top of the window`

I'm on linux now) Don't know what you're talking about.

`that still work`

... and brokes the browser as a bonus)

**Comment by ddnexus** [comment]
You are making too many wrong assumptions:

1. "there's no sense in waiting for the fix (or asking for new features) here". I am not waiting for any fix, nor new feature here, but still... some code in this repo still work better than the still missing fix on the Vivaldi side
2. "You could have already learn JS yourself and write a simple, but working script)". I learned js in the last 25 years and I still this DOES NOT give me the time to actually using it, especially when it has to be applied as a hack to an app that I didn't write
3. "and brokes the browser as a bonus". The working solution that I proposed on my previous post does work... writing exactly 0 lines of code

"I'm on linux now) Don't know what you're talking about.". 
FYI: Settings > Appearance > Menu Position > Vivaldi Button. It replaces the menu with an icon, still leaving the full (empty) menu bar across the screen, so totally useless.

"I've already wrote a script for current search icon displaying and I'm gonna write another one for passive scrolling".
Great! Where are the repo links?

**Comment by jdunne525** [comment]
If anybody still cares about this project I created a fork with the crappy workaround I described above.  The installer is working as of the latest Vivaldi 1.15.1147.64.  
Note the only script that is presently loaded is multi-line-tabs.css, though its trivial to add another one by just editing the load_hooks.js file after installation.

https://github.com/jdunne525/VivaldiHooks

**Comment by Kabouik** [comment]
Thanks @jdunne525!

**Comment by justdanpo** [comment]
Ok, I believe now it works, though most of hooks should be reimplemented.
commit 3fd9db94546d9ae85cec083d4b8e1339bf5a2318

**Comment by jdunne525** [comment]
Woah.  @justdanpo is back.  Thanks for resurrecting this.  BTW, multiline-tabs now shows an extra row for some reason in latest Vivaldi v2.6.  It still works, just wastes some screen space.
