### ISSUE TITLE
qc-close-tab: Possible to close tab with Delete key?

### ISSUE THREAD

**Issue by Pathduck** [justdanpo/VivaldiHooks#34]
Would it be possible to add a feature to this hook to allow closing tabs with Delete? It would be a massive timesaver :)

Oh and thanks for your excellent work mate :)

**Comment by justdanpo** [comment]
I'm not sure Delete is good choice as it's used in the QuickCommands textbox. Shift+Delete may be?

**Comment by Pathduck** [comment]
Shift+Delete is definitely a better choice :)

My original thought was that the use of Del would be rare, most users would just use backspace. But you're absolutely right, best not to mess with the standard editing keys.

**Comment by justdanpo** [comment]
Done

**Comment by Pathduck** [comment]
Wow, you're fast! :) Thanks so much, I just tested and it works 👍 

One kind of minor problem when using the keyboard though, is that k/b focus is not returned to the page after closing QC again with F2. It also happens when using the close X button so I assume this was there earlier as well?

Is there some way to make the focus return to the page after exiting the QC?

**Comment by justdanpo** [comment]
Please check the latest version

**Comment by Pathduck** [comment]
Just updated, it seems to work now, awesome, thanks again mate 😄 🥇
