### ISSUE TITLE
What about the move-V-button-to-addressbar?

### ISSUE THREAD

**Issue by ddnexus** [justdanpo/VivaldiHooks#39]
Hi @justdanpo,
glad that you restarted the project!

There was a `move-V-button-to-addressbar.js` that was doing a very useful thing, especially when you use the vertical tabs in full screen without full menu.

In that case the menus are under an icon, but you have nothing else in the bar, and that's is ugly and a big waste of space. I added a few CSS rules in the browser.html that remove it completely:
```
#browser #tabs-container.top{ padding-left: 0px }
#browser.native:not(.tabs-top):not(.horizontal-menu) #header { display: none }
#titlebar > .vivaldi { display: none }
#browser.horizontal-menu .vivaldi-addressbar {display: none }
```
However that is not optimal, since you have to rely to the `Alt` key to get the menus.

Having the icon baack in the addresbar would completely solve the problem.

**Comment by justdanpo** [comment]
I'm not sure I understand you. Do you mean empty title bar is displayed in maximized window? If so I need to know which settings lead to this.
In non-maximized windows we need to have something we can drag windows by.

**Comment by ddnexus** [comment]
Not the window title bar, I mean the bar usually used for tabs. When the tabs are vertical is totally useless and contains only the icon for the Vivaldi menu. The old move-V-button-to-addressbar hook was moving it in the address bar area an hiding the bar that contained it.

**Comment by justdanpo** [comment]
In April I added `move-V-button-to-addressbar.js` functionality to `move-window-buttons-maximized.js`. Check out [this wiki page](https://github.com/justdanpo/VivaldiHooks/wiki/Hooks) for hooks descrption, may be you'll find anything useful.

**Comment by ddnexus** [comment]
I saw that and I tried to activate it, but it doesn't do anything to the V-button. Did I miss anything?

**Comment by ddnexus** [comment]
I see... I am using the linux version and looking into the hook code it apply the display:none only to non native window. in my case the css should be:
```css
#browser:not(.popup):not(.horizontal-menu):not(.tabs-top).maximized #header { display: none; }
```
Then the .MaximizedWindowButtons styles are only for windows, so no mac nor linux.

I think I can create a new hook for my need by just cherry-picking  and adapting what I need from your code. Thank you.

**Comment by justdanpo** [comment]
It moves V button to the address bar
![screenshot](https://github.com/justdanpo/VivaldiHooks/wiki/images/hooks/move-window-buttons-maximized.js.png)

It doesn't do it in 2 cases:
- tabbar is placed at the top (as there is not separate titlebar in this setup)
- Vivaldi window is not maximized: we need a place we can use to move window via drag'n'drop

Talking about the second one I could replace it with a narrow bar of the same color as the address bar.

**Comment by ddnexus** [comment]
> Vivaldi window is not maximized: we need a place we can use to move window via drag'n'drop

If it is using a native window it has its own window title bar to drag it around, so it could be removed also in that case.

**Comment by justdanpo** [comment]
Please check the latest update

**Comment by ddnexus** [comment]
The last update fixed it! Than you!
