### ISSUE TITLE
Guest mode

### ISSUE THREAD

**Issue by justdanpo** [justdanpo/VivaldiHooks#40]
All hooks in guest mode are enabled by default. There is no way to modify guest mode settings.
https://forum.vivaldi.net/topic/11298/vivaldihooks-more-useful-mods/266?_=1591972922101
May be hooks should be disabled in guest mode at all, but I'm not sure.

**Comment by Pathduck** [comment]
Just to give my opinion on this (why not...), hooks should be disabled in Guest Mode (if technically possible). Guest Mode is used when *another person* wants to borrow the browser. And some of use use it also for testing website and UI issues in a "clean" profile which is kind of pointless if lots of hooks are loaded. Just my 2€ :)
