### ISSUE TITLE
speeddial-downloads.js bugs in Vivaldi 3.3.2001.3

### ISSUE THREAD

**Issue by ian-coog** [justdanpo/VivaldiHooks#41]
I just updated from 3.2 to the first 3.3 snapshot
https://vivaldi.com/blog/snapshots/desktop/whole-page-blocking-support-vivaldi-browser-snapshot-2001-3/
I had, among other various mods, also speeddial-downloads.js enabled. By opening a new tab, vivaldi shows the splash screen and all you can do is closing and reopening, luckily it's not a permanent lock. I disabled all hooks and the problem doesn't show.
After enabling all one by one I noticed speeddial-downloads.js is the culprit.
For now I keep it disabled,

**Comment by justdanpo** [comment]
Please check the update

**Comment by ian-coog** [comment]
Updated, reenabled speeddial-downloads.js and new tab now works normally, good work.
