### ISSUE TITLE
VivaldiHooks breaks new profiles in Snapshot 3.3.2020.3

### ISSUE THREAD

**Issue by Pathduck** [justdanpo/VivaldiHooks#43]
Enabling VivaldiHooks in the latest snapshot will break the creation of new profiles and just lead to a blank UI with the V logo.

**Comment by justdanpo** [comment]
Try removing unicode-url.js

**Comment by Pathduck** [comment]
That works 👍 
But why would it do that, I don't even have it enabled in the list of hooks ? 😕

**Comment by justdanpo** [comment]
All hooks are enabled by default, new user gets default settings

**Comment by Pathduck** [comment]
Oh right, of course :) 
Unicode-URL is really small, are you able to figure out what breaks?

**Comment by justdanpo** [comment]
There is a separate issue for unicode-url.js, so I'm closing this one
