### ISSUE TITLE
QC-close-tab no longer works in 3.5.2088.7 snapshot.

### ISSUE THREAD

**Issue by Pathduck** [justdanpo/VivaldiHooks#49]
It seems the team did some changes to the QC this time around, and tabs can no longer be closed from the QC, neither by clicking the X or Del key.

It's a really useful feature (it should be default in V IMO...) and sad to see it broken. 

Any chance for an easy fix?

**Comment by justdanpo** [comment]
Please check the latest update

**Comment by Pathduck** [comment]
Genius! It works again 👍

**Comment by Pathduck** [comment]
@justdanpo I'm really sorry, but it looks like the latest snapshot broke it again... 😞
