### ISSUE TITLE
Documentation : Install on MacOS/OSX and dev tools : remote debug mode

### ISSUE THREAD

**Issue by HereThereBeMonsters** [justdanpo/VivaldiHooks#5]
I installed VivaldiHooks mainly for the ability to dock the Chrome dev tools on the right or bottom of the window. It is great and I might finally make the jump and give up Chrome entirely. Some of the other mods also look nice.

However there was a couple of undocumented difficulties, you might want to add that to the readme:

### 1. Path on MacOS

The path to which to copy the files (manual install) is:

`/Applications/Vivaldi.app/Contents/Versions/{version}/Framework.framework/Resources/vivaldi`

(Where of course `{version}` represents the actual version number)

This was not very clear form the readme and a post on the Vivaldi forum put me on the right track.

### 2. Docked dev tools : enable remote debug

For some reason it is necessary to manually enable remote debugging on a specific port for the docked dev tools to work. Fortunately the error message is informative and it is easy to achieve:

Start Vivaldi with the following command (on MacOS):

`open /Applications/Vivaldi.app --args --remote-debugging-port=9222`

Or create a bash script:

```
#!/usr/bin/env bash

open /Applications/Vivaldi.app --args --remote-debugging-port=9222

```

You can then enjoy the docked dev tools.

**Comment by justdanpo** [comment]
Am I right that there should be `/Vivaldi Framework.framework/` instead of `/Framework.framework/`?

**Comment by HereThereBeMonsters** [comment]
Yes that is right, cut-paste problem, sorry.

**Comment by justdanpo** [comment]
Updated paths in README.md
