### ISSUE TITLE
loading.js

### ISSUE THREAD

**Issue by fds39** [justdanpo/VivaldiHooks#51]
I had to remove this hook which crashed the latest snapshot 3.5.2131.8 (Official version) (64 bits)
https://forum.vivaldi.net/post/428015

**Comment by guigirl42** [comment]
Same here.
https://forum.vivaldi.net/post/428029

**Comment by justdanpo** [comment]
Yeah. Need to redisign `require` function.

**Comment by justdanpo** [comment]
commit 208da9f1e3a4cd98375a9d8a651d95d89e48c75f

**Comment by guigirl42** [comment]
Thank you. Now `loading.js` no longer crashes Snapshot 3.5.2131.8 / Chrome 87.0.4280.88, but another of your newly updated hooks, `bookmarks-button.js`, seems to be broken. It crashes Stable, & whilst Snapshot launches with it, once activated it does nothing when the icon is clicked. Pls see my post: https://forum.vivaldi.net/post/428847

**Comment by justdanpo** [comment]
I'm sorry I cannot reproduce it. The only issue I experience is issue #53: selected mode is not displayed in configuration until I click a radiobutton. `bookmarks-button.js` may be used in [2 modes](https://github.com/justdanpo/VivaldiHooks/wiki/Hooks#bookmarks-buttonjs), are you sure you're trying using the one you have configured?

**Comment by justdanpo** [comment]
As `loading.js` is fixed I'm closing this issue. If you have more details about reproducing the bug please submit a new one.
