### ISSUE TITLE
Multiline-tabs.css

### ISSUE THREAD

**Issue by Ladergorn** [justdanpo/VivaldiHooks#52]
Multiline tabs not working for me with Vivaldi 3.5 If I have tabs at the top, I see no tabs at all. If tabs at bottom, I see tabs, but all in a single row.

**Comment by justdanpo** [comment]
Works for me. Have you tried disabling other mods?

**Comment by justdanpo** [comment]
Ok, I've managed to reproduce similar issue in 3.6.2137.3

**Comment by justdanpo** [comment]
@Ladergorn please check the latest version

**Comment by Ladergorn** [comment]
Not working I'm afraid. Vivaldi 3.6.2137.3 64 bit
If tabs at top set, no tabs at top and I lose all top row of browser
If tabs at bottom set, I have tabs but no multi row.
![vivaldi no css ](https://user-images.githubusercontent.com/40541051/103175474-20401e80-4862-11eb-94df-f489e046617f.jpeg)
![vivaldi css 2](https://user-images.githubusercontent.com/40541051/103175476-233b0f00-4862-11eb-80c8-7b73b8138619.jpeg)
![vivaldi css 1](https://user-images.githubusercontent.com/40541051/103175479-2504d280-4862-11eb-82b8-031e0abaafe9.jpeg)

**Comment by justdanpo** [comment]
So do you have other mods installed? The latest version works for me in both 3.5 and 3.6.2137.3

**Comment by Ladergorn** [comment]
I have a line in the custom.css that alters the unread tabs title text to be red and italic:

.tab-position .tab.unread .tab-header .title {color: red; font-style: italic !important;}

If I disable this, multiline is working properly. Strange that it was working OK previously. Can you suggest a workaround?

Many thanks

**Comment by justdanpo** [comment]
I don't see how this line may cause the issue. Two guesses:

1. lines before this one are parts of css selector so removing the line modifies selector of the following block (the real cause) and "disables" it
2. your custom.css contains errors (extra charaters or something else) and removing this line makes the real cause invalid. Try checking you css with [online] css validator.
