### ISSUE TITLE
bookmarks-button.js: radioGroup in settings doesn't display initial value

### ISSUE THREAD

**Issue by justdanpo** [justdanpo/VivaldiHooks#53]

**Comment by tiosgz** [comment]
It seems to collide with the *Bookmark bar display* setting — when I choose one option in the newly added group, there’s no option ticked in *bookmark bar display*, & the other way around.

Haven’t checked if it’s the same internally yet.

**Comment by justdanpo** [comment]
Thanks @tiosgz
