### ISSUE TITLE
speeddial-downloads.js breaks Vivaldi 3.6.2165.3

### ISSUE THREAD

**Issue by ian-coog** [justdanpo/VivaldiHooks#54]
Just updated Vivaldi 3.6.2165.3 snapshot, speeddial-downloads.js causes speed dial on new tab to fail, appears
"
An error occurred
Please consider reporting the issue to help us fix it
"

**Comment by justdanpo** [comment]
commit 9f8da72

**Comment by ian-coog** [comment]
Thanks, the fix allows also speeddial-downloads.js to work now
