### ISSUE TITLE
Speeddial-spacing broken in latest V snapshot (2209.3)

### ISSUE THREAD

**Issue by Pathduck** [justdanpo/VivaldiHooks#58]
As I'm sure you're aware, V devs did a lot of changes to the Start Page in the last snapshot, effectively breaking the `speeddial-spacing` hook. It's not a major disaster, but it was one of my favourite hooks because it allowed tweaking of the margins between the dials.

Not sure what can be done, but probably a good idea to hold off on any fixes until they've finished "tweaking" the SD.

I might have a look but I'm afraid my JS skills are not up to par with this...

**Comment by ian-coog** [comment]
see https://github.com/justdanpo/VivaldiHooks/issues/59
