### ISSUE TITLE
speeddial-spacing incompatible with Vivaldi 3.7 Snapshot

### ISSUE THREAD

**Issue by coaperator** [justdanpo/VivaldiHooks#59]
the new version has a new grid system on express panel, please fix it

**Comment by ian-coog** [comment]
fix proposed by potmeklecbohdan on
https://forum.vivaldi.net/topic/11298/vivaldihooks-more-useful-mods/311
https://github.com/tiosgz/VivaldiHooks/blob/v37/vivaldi/hooks/speeddial-spacing.js
seems correctly working with Vivaldi 3.7.2218.3

**Comment by coaperator** [comment]
@ian-coog nice, it`s working!
