### ISSUE TITLE
download-tab.js not working

### ISSUE THREAD

**Issue by markybob** [justdanpo/VivaldiHooks#6]
1.5.658.42 linux 64-bit
i enabled download-tab.js but it still uses the sidebar and not vivaldi://downloads
any idea why or what i can try? i tested by going to:
https://www.debian.org/devel/debian-installer/
and then clicking on any of the iso images. 
thanks.

**Comment by justdanpo** [comment]
vivaldi://settings/downloads/

**Comment by markybob** [comment]
thanks
