### ISSUE TITLE
Hook `move-window-buttons-maximized.js` broke in Snapshot 3.8.2238.3.

### ISSUE THREAD

**Issue by guigirl42** [justdanpo/VivaldiHooks#62]
This hook worked well in Snapshots up to & including 3.7.2218.45, & still in Stable 3.7.2218.453.7.2218.45. Unfortunately it is incompatible with the new Snapshot 3.8.2238.3, which actually then fails to fully launch unless i disable this specific hook [see pictures posted here https://forum.vivaldi.net/post/460137 & https://forum.vivaldi.net/post/460095].

**Comment by guigirl42** [comment]
Woohoo, ~~solved~~/worked-around! 
Despite this being old code & V-SS having undergone so much change since this CSS was first written by @LonM [who still *rocks*!], **it still works even now**; https://forum.vivaldi.net/post/375845. Thus, once again this fundamental V UI design flaw can be worked-around, to eliminate the otherwise top space-waste with vertical tabs. Woohoo.

**Comment by justdanpo** [comment]
Fixed in April
