### ISSUE TITLE
Speeddial-spacing: Drag+drop reordering does not work as expected.

### ISSUE THREAD

**Issue by Pathduck** [justdanpo/VivaldiHooks#69]
Since a couple V versions ago, probably since the big changes to SD code, the reordering of dials using drag and drop fails. Dials can only be dragged to the first position.

Usually I keep it pretty static, but sometimes I mistakenly drag a dial, and I have to disable the spacing hook and restart to set the dials back to where they are supposed to be.

Would be really nice if this can be fixed. I might need to disable drag+drop reordering to avoid accidental drags.

For reference here's my SD settings:
![image](https://user-images.githubusercontent.com/1493836/120866441-3d56e700-c590-11eb-849d-969b43cd974b.png)

**Comment by tiosgz** [comment]
It seems to be working well for me (using the hook version at #65 and Vivaldi 4.0.2312.11).

**Comment by Pathduck** [comment]
@tiosgz That's really strange. I jus ttested in a clean unmodded profile of the latest Snapshot `4.0.2312.13`. After enabling only speeddial-spacing.js and restarting it stops working properly - I can only place the dial in the first position.

I might make a video of it happening.

**Comment by tiosgz** [comment]
Are you using the `speeddial-spacing.js` found at #65? Note that it isn’t the same as on master.

**Comment by Pathduck** [comment]
Oh, no I'm just using the master. How would I pull in only your change without having to clone my own repo?

**Comment by tiosgz** [comment]
I guess you can just download the file & replace it. https://github.com/tiosgz/VivaldiHooks/blob/v37/vivaldi/hooks/speeddial-spacing.js

**Comment by Pathduck** [comment]
Yeah - I just tried and it works again as expected! 👍 

I guess we really need that pull committed to master.

**Comment by justdanpo** [comment]
Merged
