### ISSUE TITLE
Docked dev tools : clipboard (cut and paste) is disabled.

### ISSUE THREAD

**Issue by HereThereBeMonsters** [justdanpo/VivaldiHooks#7]
Finally, I was able to use Vivaldi to develop my web apps! I was very happy and the world had become a slightly better place...

Alas! It turns out that when using the mod to dock the dev tools inside the main window, the clipboard is disabled. When you try to copy something, like a URL for example, by right-clicking and select the copy option, there is an error message in the console that says:

```
Clipboard is not enabled in hosted mode. Please inspect using chrome://inspect 
```

This greatly reduces the usefulness of the mod. Event though I don't need to copy stuff all the times, when I do (e.g. error message or a URL) I don't want to have to open a new Dev Tools or Chrome window and reproduce the whole case every time.

So for now, back to Chrome it is.

I hope there is a way to overcome this limitation, but it looks as if it something deeply rooted in the Chrome Dev Tools themselves.

**Comment by justdanpo** [comment]
Yeah. I can't do anything with it (at least without modifying Chromium).
