### ISSUE TITLE
After today's update to the latest version (4.0.2312.24 Stable channel 64-bit) , the "open download tab instead of download panel" stop works.

### ISSUE THREAD

**Issue by buglocker** [justdanpo/VivaldiHooks#70]
Hello. 
After today's update to the latest version (4.0.2312.24 Stable channel 64-bit) , 
the "open download tab instead of download panel" stop works.
Thanks.

**Comment by justdanpo** [comment]
Works for me, the only issue I can see downloads tab is opened multiple times - one tab per download.

**Comment by buglocker** [comment]
1) Which settings do you use at Settings/downloads when the option is enable and works ?
![downloads](https://user-images.githubusercontent.com/85626757/121377410-fe87af00-c94a-11eb-9b29-543b600bedbe.png)

2) After you enable the option at Settings , where do you have (path) the download-tab.js file ? I got it at C:\Users\myusername\AppData\Local\Vivaldi\Application\4.0.2312.24\resources\vivaldi\hooks\download-tab.js. Is that correct ?

**Comment by justdanpo** [comment]
1. Required settings are: [x] open download tab automatically, [x] open download in new tab instead of panel. Your screenshot doesn't contain the second one (which is added by hook and is not localized) so you haven't installed jdhooks correctly or you have a modified copy of download-tab.js.
2. Installation section explains that https://github.com/justdanpo/VivaldiHooks though it doesn't describe how to download complete jdhooks archive (green "code" button at the top of the page -> "download zip")
3. Yes

**Comment by buglocker** [comment]
1) With these settings and dont work : 
![2](https://user-images.githubusercontent.com/85626757/121382159-02b5cb80-c94f-11eb-9cad-c6847d4c0c16.png)
![2](https://user-images.githubusercontent.com/85626757/121382172-05b0bc00-c94f-11eb-80c2-09b1feb74818.png)

2) I have installed VH with installhooks.bat.

3) I will try if the problem persists with all extensions disabled.
Thanks.

**Comment by buglocker** [comment]
> 1. Required settings are: [x] open download tab automatically, [x] open download in new tab instead of panel. Your screenshot doesn't contain the second one (which is added by hook and is not localized) so you haven't installed jdhooks correctly or you have a modified copy of download-tab.js.
> 2. Installation section explains that https://github.com/justdanpo/VivaldiHooks though it doesn't describe how to download complete jdhooks archive (green "code" button at the top of the page -> "download zip")
> 3. Yes

I tested with extensions disabled and/or mods disabled , and the problem persists.

**Comment by justdanpo** [comment]
Your last by one screenshot doesn't contain a settings added by the hook ("open download in new tab instead of panel"). Have you restarted Vivaldi after enabling the hook?

**Comment by buglocker** [comment]
" Have you restarted Vivaldi after enabling the hook? "
Yes.

**Comment by justdanpo** [comment]
Try installing the latest version.
If it dosn't work run Vivaldi with `--debug-packed-apps` command line key, reproduce test steps, right click on any Vivaldi UI element, choose "inspect" and then show me console log.

**Comment by buglocker** [comment]
1) I already have the latest version
2) How i can "reproduce test steps" ?

**Comment by justdanpo** [comment]
1. According to your first screenshot you had a modified version of jdhooks. If you have the latest version got from exactly the same source it may be outdated. The latest version from my repository: https://github.com/justdanpo/VivaldiHooks/archive/refs/heads/master.zip
2. Open download settings to make hooks' settings appear; download something to open download tab/panel.

**Comment by buglocker** [comment]
I downloaded the latest version from your link , and it solved. 
Thanks.
