### ISSUE TITLE
debian install path

### ISSUE THREAD

**Issue by markybob** [justdanpo/VivaldiHooks#8]
I've been putting it in /opt/vivaldi-snapshot/resources/ but when apt-get installs an update, it gets wiped out. is there some local path that i can put this in so the package manager doesn't remove it?  somewhere in ~/.config/vivaldi-snapshot/  ? (i tried ~/.config/vivaldi-snapshot with no luck)
thanks

**Comment by justdanpo** [comment]
No, there is no such path.
There is a feature request on bugtracker: VB-20579 Need a way to restyle Vivaldi that won't be erased by updates
